Repository kcw36/lmnh_plant_health, pull requests merged in 2025-06, with the labels that each got.

#37 [PR] Add Architecture Diagram.
  architecture/README.md
  architecture/architecture_diagram.png
Labels: documentation, enhancement

#56 [PR] Automated Deployment
  .github/workflows/python_ci_cd.yaml
  dashboard/requirements.txt
  pipelines/longterm/requirements.txt
  pipelines/shortterm/requirements.txt
  report/requirements.txt
Labels: enhancement

#53 [PR] Extract short term files
  .gitignore
  pipelines/shortterm/README.md
  pipelines/shortterm/extract_short.py
  pipelines/shortterm/requirements.txt
  pipelines/shortterm/skipped_plants.log
  pipelines/shortterm/test_extract_short.py
Labels: documentation, enhancement

#82 [PR] Implement historic transform module
  pipelines/longterm/README.md
  pipelines/longterm/conftest.py
  pipelines/longterm/test_transform.py
  pipelines/longterm/transform.py
Labels: documentation, enhancement

#85 [PR] Update ERD
  architecture/database/short_term_erd.png
Labels: bug

#107 [PR] Report Script
  architecture/terraform/infrastructure/README.md
  architecture/terraform/infrastructure/main.tf
  report/Dockerfile
  report/data.py
  report/report.py
  report/requirements.txt
Labels: enhancement

#108 Dashboard
  architecture/architecture_diagram.png
  architecture/terraform/infrastructure/main.tf
  architecture/terraform/infrastructure/variables.tf
  dashboard/Dockerfile
  dashboard/README.md
  dashboard/Real_Time_Data_Dashboard.py
  dashboard/dashboard.py
  dashboard/data.py
  dashboard/historic_data.py
  dashboard/pages/2_Historic_Data_Dashboard.py
  dashboard/requirements.txt
  dashboard/test_dashboard.py
  dashboard/visualisations.py
Labels: enhancement
